package CollectionClass;

public class TestThrowAndThrows  
{  
    // defining a user-defined method  
    // which throws ArithmeticException  
    static int method() throws ArithmeticException  
    {  	        int div = m / n;  
   
        System.out.println("Inside the method()");  
        throw new ArithmeticException("throwing ArithmeticException");  
        return div;  
    }  
    //main method  
    public static void main(String args[])  
    {  
        try  
        {  
            method();  
        }  
        catch(ArithmeticException e)  
        {  
            System.out.println("caught in main() method");  
        }  
    }  
}  
